// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    public partial class certificate
    {
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string name { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string image { get; set; }
        [Key]
        public int coachID { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("certificates")]
        public virtual coach coach { get; set; }
    }
}