// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Client_coach_WOsubscription")]
    public partial class Client_coach_WOsubscription
    {
        [Key]
        public int clientID { get; set; }
        [Key]
        public int coachID { get; set; }
        [Key]
        public int subID { get; set; }
        public bool? accept { get; set; }
        public int? rating { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime startDate { get; set; }
        [Unicode(false)]
        public string comment { get; set; }

        [ForeignKey("clientID")]
        [InverseProperty("Client_coach_WOsubscriptions")]
        public virtual client client { get; set; }
        [ForeignKey("coachID")]
        [InverseProperty("Client_coach_WOsubscriptions")]
        public virtual coach coach { get; set; }
        [ForeignKey("subID")]
        [InverseProperty("Client_coach_WOsubscriptions")]
        public virtual Workout_Subscription sub { get; set; }
    }
}