// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Client_Meal_NSub")]
    public partial class Client_Meal_NSub
    {
        [Key]
        public int clientID { get; set; }
        [Key]
        public int mealID { get; set; }
        [Key]
        public int subID { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime date { get; set; }

        [ForeignKey("clientID")]
        [InverseProperty("Client_Meal_NSubs")]
        public virtual Client client { get; set; }
        [ForeignKey("mealID")]
        [InverseProperty("Client_Meal_NSubs")]
        public virtual Meal meal { get; set; }
        [ForeignKey("subID")]
        [InverseProperty("Client_Meal_NSubs")]
        public virtual Nutrition_Subscription sub { get; set; }
    }
}