// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("client_meal_sub")]
    public partial class client_meal_sub
    {
        [Key]
        public int clientID { get; set; }
        [Key]
        public int mealID { get; set; }
        [Key]
        public int subID { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime date { get; set; }

        [ForeignKey("clientID")]
        [InverseProperty("client_meal_subs")]
        public virtual client client { get; set; }
        [ForeignKey("mealID")]
        [InverseProperty("client_meal_subs")]
        public virtual meal meal { get; set; }
        [ForeignKey("subID")]
        [InverseProperty("client_meal_subs")]
        public virtual nutrition_subscription sub { get; set; }
    }
}