// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CoachingApp.Identity;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("client")]
    public partial class client
    {
        public client()
        {
            Client_coach_Nsubscriptions = new HashSet<Client_coach_Nsubscription>();
            Client_coach_WOsubscriptions = new HashSet<Client_coach_WOsubscription>();
            client_meal_subs = new HashSet<client_meal_sub>();
            client_workout_subs = new HashSet<client_workout_sub>();
        }

        [Key]
        public int id { get; set; }
        [ForeignKey("User")]
        public string UserId { get; set; }
        public int age { get; set; }
        [StringLength(50)]
        public string lastName { get; set; }
        [StringLength(50)]
        public string firstName { get; set; }
        [StringLength(100)]
        public string email { get; set; }
        [StringLength(20)]
        public string mobileNum { get; set; }
        public bool? gender { get; set; }
        [StringLength(30)]
        public string city { get; set; }
        [StringLength(30)]
        public string country { get; set; }
        public double? height { get; set; }
        public double? weight { get; set; }
        [StringLength(30)]
        public string image { get; set; }

        [InverseProperty("client")]
        public virtual ICollection<Client_coach_Nsubscription> Client_coach_Nsubscriptions { get; set; }
        [InverseProperty("client")]
        public virtual ICollection<Client_coach_WOsubscription> Client_coach_WOsubscriptions { get; set; }
        [InverseProperty("client")]
        public virtual ICollection<client_meal_sub> client_meal_subs { get; set; }
        [InverseProperty("client")]
        public virtual ICollection<client_workout_sub> client_workout_subs { get; set; }
        public virtual IdentityApplicationUser User { get; set; }
    }
}