// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CoachingApp.Identity;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Client")]
    public partial class Client
    {
        public Client()
        {
            Client_Meal_NSubs = new HashSet<Client_Meal_NSub>();
            Client_NSubs = new HashSet<Client_NSub>();
            Client_WSubs = new HashSet<Client_WSub>();
            Client_Workout_WSubs = new HashSet<Client_Workout_WSub>();
        }

        [Key]
        public int id { get; set; }
        [ForeignKey("User")]
        public Guid userId { get; set; }
        public int age { get; set; }
        [StringLength(50)]
        public string lastName { get; set; }
        [StringLength(50)]
        public string firstName { get; set; }
        [StringLength(100)]
        public string email { get; set; }
        [StringLength(20)]
        public string mobileNum { get; set; }
        public bool? gender { get; set; }
        [StringLength(30)]
        public string city { get; set; }
        [StringLength(30)]
        public string country { get; set; }
        public double? height { get; set; }
        public double? weight { get; set; }
        [StringLength(30)]
        public string image { get; set; }
        public virtual IdentityApplicationUser User { get; set; }

        [InverseProperty("client")]
        public virtual ICollection<Client_Meal_NSub> Client_Meal_NSubs { get; set; }
        [InverseProperty("client")]
        public virtual ICollection<Client_NSub> Client_NSubs { get; set; }
        [InverseProperty("client")]
        public virtual ICollection<Client_WSub> Client_WSubs { get; set; }
        [InverseProperty("client")]
        public virtual ICollection<Client_Workout_WSub> Client_Workout_WSubs { get; set; }
    }
}