// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("client_workout_sub")]
    public partial class client_workout_sub
    {
        [Key]
        public int clientID { get; set; }
        [Key]
        public int workoutID { get; set; }
        [Key]
        public int subID { get; set; }
        public bool? status { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string clientNotes { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime date { get; set; }

        [ForeignKey("clientID")]
        [InverseProperty("client_workout_subs")]
        public virtual client client { get; set; }
        [ForeignKey("subID")]
        [InverseProperty("client_workout_subs")]
        public virtual Workout_Subscription sub { get; set; }
        [ForeignKey("workoutID")]
        [InverseProperty("client_workout_subs")]
        public virtual Workout workout { get; set; }
    }
}