// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CoachingApp.Identity;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("coach")]
    public partial class coach
    {
        public coach()
        {
            Client_coach_Nsubscriptions = new HashSet<Client_coach_Nsubscription>();
            Client_coach_WOsubscriptions = new HashSet<Client_coach_WOsubscription>();
            Excercises = new HashSet<Excercise>();
            Workout_Sets = new HashSet<Workout_Set>();
            Workout_Subscriptions = new HashSet<Workout_Subscription>();
            Workouts = new HashSet<Workout>();
            certificates = new HashSet<certificate>();
            meals = new HashSet<meal>();
            nutrition_subscriptions = new HashSet<nutrition_subscription>();
        }

        [Key]
        public int id { get; set; }
        [ForeignKey("User")]
        public string UserId { get; set; }
        public int age { get; set; }
        [StringLength(50)]
        public string lastName { get; set; }
        [StringLength(50)]
        public string firstName { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string email { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string mobileNum { get; set; }
        public bool? gender { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string city { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string country { get; set; }
        public int? yearsExperience { get; set; }
        public double? rating { get; set; }
        public int? NumberOfRating { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string image { get; set; }

        [InverseProperty("coach")]
        public virtual ICollection<Client_coach_Nsubscription> Client_coach_Nsubscriptions { get; set; }
        [InverseProperty("coach")]
        public virtual ICollection<Client_coach_WOsubscription> Client_coach_WOsubscriptions { get; set; }
        [InverseProperty("coach")]
        public virtual ICollection<Excercise> Excercises { get; set; }
        [InverseProperty("coach")]
        public virtual ICollection<Workout_Set> Workout_Sets { get; set; }
        [InverseProperty("coach")]
        public virtual ICollection<Workout_Subscription> Workout_Subscriptions { get; set; }
        [InverseProperty("coach")]
        public virtual ICollection<Workout> Workouts { get; set; }
        [InverseProperty("coach")]
        public virtual ICollection<certificate> certificates { get; set; }
        [InverseProperty("coach")]
        public virtual ICollection<meal> meals { get; set; }
        [InverseProperty("coach")]
        public virtual ICollection<nutrition_subscription> nutrition_subscriptions { get; set; }
        public virtual IdentityApplicationUser User { get; set; }

    }
}