// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Excercise")]
    public partial class Excercise
    {
        public Excercise()
        {
            workout_excercises = new HashSet<workout_excercise>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string description { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string link { get; set; }
        public int? coachID { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("Excercises")]
        public virtual coach coach { get; set; }
        [InverseProperty("excercise")]
        public virtual ICollection<workout_excercise> workout_excercises { get; set; }
    }
}