// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Excercise")]
    public partial class Excercise
    {
        public Excercise()
        {
            Workout_Exercises = new HashSet<Workout_Exercise>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string description { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string link { get; set; }
        public int coachID { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("Excercises")]
        public virtual Coach coach { get; set; }
        [InverseProperty("excercise")]
        public virtual ICollection<Workout_Exercise> Workout_Exercises { get; set; }
    }
}