// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("meal")]
    public partial class meal
    {
        public meal()
        {
            client_meal_subs = new HashSet<client_meal_sub>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string description { get; set; }
        public int? coachID { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("meals")]
        public virtual coach coach { get; set; }
        [InverseProperty("meal")]
        public virtual ICollection<client_meal_sub> client_meal_subs { get; set; }
    }
}