// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("nutrition_subscription")]
    public partial class nutrition_subscription
    {
        public nutrition_subscription()
        {
            Client_coach_Nsubscriptions = new HashSet<Client_coach_Nsubscription>();
            client_meal_subs = new HashSet<client_meal_sub>();
        }

        [Key]
        public int id { get; set; }
        public int? duration { get; set; }
        public int? price { get; set; }
        public int? coachID { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("nutrition_subscriptions")]
        public virtual coach coach { get; set; }
        [InverseProperty("sub")]
        public virtual ICollection<Client_coach_Nsubscription> Client_coach_Nsubscriptions { get; set; }
        [InverseProperty("sub")]
        public virtual ICollection<client_meal_sub> client_meal_subs { get; set; }
    }
}