// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    public partial class workouts_in_set
    {
        [Key]
        public int workout_set_id { get; set; }
        [Key]
        public int workoutID { get; set; }
        public int rank { get; set; }

        [ForeignKey("workoutID")]
        [InverseProperty("workouts_in_sets")]
        public virtual Workout workout { get; set; }
        [ForeignKey("workout_set_id")]
        [InverseProperty("workouts_in_sets")]
        public virtual Workout_Set workout_set { get; set; }
    }
}