// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Workout")]
    public partial class Workout
    {
        public Workout()
        {
            Client_Workout_WSubs = new HashSet<Client_Workout_WSub>();
            Workout_Exercises = new HashSet<Workout_Exercise>();
            Workout_WorkoutSets = new HashSet<Workout_WorkoutSet>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string notes { get; set; }
        public int? duration { get; set; }
        public int? coachID { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string name { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("Workouts")]
        public virtual Coach coach { get; set; }
        [InverseProperty("workout")]
        public virtual ICollection<Client_Workout_WSub> Client_Workout_WSubs { get; set; }
        [InverseProperty("workout")]
        public virtual ICollection<Workout_Exercise> Workout_Exercises { get; set; }
        [InverseProperty("workout")]
        public virtual ICollection<Workout_WorkoutSet> Workout_WorkoutSets { get; set; }
    }
}