// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Workout_Subscription")]
    public partial class Workout_Subscription
    {
        public Workout_Subscription()
        {
            Client_WSubs = new HashSet<Client_WSub>();
            Client_Workout_WSubs = new HashSet<Client_Workout_WSub>();
        }

        [Key]
        public int id { get; set; }
        public int? duration { get; set; }
        public int? price { get; set; }
        public int? coachID { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("Workout_Subscriptions")]
        public virtual Coach coach { get; set; }
        [InverseProperty("sub")]
        public virtual ICollection<Client_WSub> Client_WSubs { get; set; }
        [InverseProperty("sub")]
        public virtual ICollection<Client_Workout_WSub> Client_Workout_WSubs { get; set; }
    }
}