// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Workout_Exercise")]
    public partial class Workout_Exercise
    {
        [Key]
        public int workoutID { get; set; }
        [Key]
        public int excerciseID { get; set; }
        public int? sets { get; set; }
        public int? reps { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string notes { get; set; }
        [Key]
        public int rank { get; set; }

        [ForeignKey("excerciseID")]
        [InverseProperty("Workout_Exercises")]
        public virtual Excercise excercise { get; set; }
        [ForeignKey("workoutID")]
        [InverseProperty("Workout_Exercises")]
        public virtual Workout workout { get; set; }
    }
}