// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    public partial class WorkoutSet
    {
        public WorkoutSet()
        {
            Workout_WorkoutSets = new HashSet<Workout_WorkoutSet>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string name { get; set; }
        public int coachID { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("WorkoutSets")]
        public virtual Coach coach { get; set; }
        [InverseProperty("workout_set")]
        public virtual ICollection<Workout_WorkoutSet> Workout_WorkoutSets { get; set; }
    }
}