// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Workout")]
    public partial class Workout
    {
        public Workout()
        {
            client_workout_subs = new HashSet<client_workout_sub>();
            workout_excercises = new HashSet<workout_excercise>();
            workouts_in_sets = new HashSet<workouts_in_set>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string notes { get; set; }
        public int? duration { get; set; }
        public int? coachID { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string name { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("Workouts")]
        public virtual coach coach { get; set; }
        [InverseProperty("workout")]
        public virtual ICollection<client_workout_sub> client_workout_subs { get; set; }
        [InverseProperty("workout")]
        public virtual ICollection<workout_excercise> workout_excercises { get; set; }
        [InverseProperty("workout")]
        public virtual ICollection<workouts_in_set> workouts_in_sets { get; set; }
    }
}