// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    public partial class Workout_Set
    {
        public Workout_Set()
        {
            workouts_in_sets = new HashSet<workouts_in_set>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string name { get; set; }
        public int? coachID { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("Workout_Sets")]
        public virtual coach coach { get; set; }
        [InverseProperty("workout_set")]
        public virtual ICollection<workouts_in_set> workouts_in_sets { get; set; }
    }
}