// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoachingApp.Models
{
    [Table("Workout_Subscription")]
    public partial class Workout_Subscription
    {
        public Workout_Subscription()
        {
            Client_coach_WOsubscriptions = new HashSet<Client_coach_WOsubscription>();
            client_workout_subs = new HashSet<client_workout_sub>();
        }

        [Key]
        public int id { get; set; }
        public int? duration { get; set; }
        public int? price { get; set; }
        public int? coachID { get; set; }

        [ForeignKey("coachID")]
        [InverseProperty("Workout_Subscriptions")]
        public virtual coach coach { get; set; }
        [InverseProperty("sub")]
        public virtual ICollection<Client_coach_WOsubscription> Client_coach_WOsubscriptions { get; set; }
        [InverseProperty("sub")]
        public virtual ICollection<client_workout_sub> client_workout_subs { get; set; }
    }
}